import React, { useState } from 'react';
import { Image, Pressable, StyleSheet, Text, View } from 'react-native';
import CameraCapture from './CameraCapture';
import LabeledInput from './LabeledInput';
import PrimaryButton from './PrimaryButton';
import Card from './Card';
import { colors, spacing, typography } from '../theme/tokens';
import { formatKes } from '../utils/formatters';

export default function SaleForm({ outlet, products, onSubmit, submitting, uploadProgress, uploadError, onPhotoCaptured }) {
  const [productId, setProductId] = useState(products[0]?.id || ''); const [qty, setQty] = useState('1'); const [unitPrice, setUnitPrice] = useState(String(products[0]?.defaultPrice || '')); const [photoUri, setPhotoUri] = useState(null); const selected = products.find((product) => product.id === productId); const total = Number(qty || 0) * Number(unitPrice || 0);
  function selectProduct(product) { setProductId(product.id); setUnitPrice(String(product.defaultPrice)); }
  function submitSale() { onSubmit({ outletId: outlet.id, productId, qty: Number(qty), unitPrice: Number(unitPrice), photoUri }); }
  return <View><Text style={styles.label}>Outlet</Text><Text style={styles.outlet}>{outlet.name}</Text><Text style={styles.label}>Product</Text><View style={styles.products}>{products.map((product) => <Pressable key={product.id} onPress={() => selectProduct(product)} style={[styles.product, product.id === productId && styles.productSelected]}><Text style={[styles.productText, product.id === productId && styles.productTextSelected]}>{product.name}</Text><Text style={styles.productPrice}>{formatKes(product.defaultPrice)}</Text></Pressable>)}</View><LabeledInput label="Quantity" icon="#" value={qty} onChangeText={setQty} keyboardType="numeric" placeholder="1" /><LabeledInput label="Unit price" icon="₵" value={unitPrice} onChangeText={setUnitPrice} keyboardType="decimal-pad" placeholder="0.00" /><Card style={styles.totalCard}><Text style={styles.totalLabel}>Sale total</Text><Text style={styles.total}>{formatKes(total)}</Text></Card><CameraCapture onCapture={(uri) => { setPhotoUri(uri); onPhotoCaptured?.(); }} />{photoUri ? <View style={styles.photoPreview}><Image source={{ uri: photoUri }} style={[styles.photo] /><Text style={[styles.photoStatus, uploadError && styles.photoError]}>{uploadProgress !== null ? `Uploading receipt… ${uploadProgress}%` : uploadError || 'Receipt ready to upload'}</Text></View> : null}{uploadError ? <PrimaryButton title="Retry receipt upload" loading={submitting} disabled={!productId} onPress={submitSale} variant="secondary" /> : null}<PrimaryButton title={`Save ${selected?.name || 'sale'}`} loading={submitting} disabled={!productId} onPress={submitSale} /></View>;
}
const styles = StyleSheet.create({ label: { color: colors.ink, fontFamily: typography.fontFamilyBold, fontSize: typography.small, fontWeight: '700', marginTop: spacing.md, marginBottom: spacing.xs }, outlet: { color: colors.muted, fontFamily: typography.fontFamily, fontSize: typography.body, marginBottom: spacing.sm }, products: { gap: spacing.sm, marginBottom: spacing.md }, product: { flexDirection: 'row', justifyContent: 'space-between', padding: spacing.md, borderWidth: 1, borderColor: colors.border, borderRadius: 12, backgroundColor: colors.surface }, productSelected: { borderColor: colors.primary, backgroundColor: colors.primarySoft }, productText: { color: colors.ink, fontFamily: typography.fontFamilyBold, fontWeight: '700' }, productTextSelected: { color: colors.primaryDark }, productPrice: { color: colors.muted }, totalCard: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginVertical: spacing.lg }, totalLabel: { color: colors.ink, fontFamily: typography.fontFamilyBold, fontWeight: '700' }, total: { color: colors.primary, fontFamily: typography.fontFamilyExtraBold, fontSize: 22, fontWeight: '800' }, photoPreview: { marginTop: spacing.md, marginBottom: spacing.md }, photo: { width: '100%', height: 180, borderRadius: 12, backgroundColor: colors.border }, photoStatus: { color: colors.muted, fontFamily: typography.fontFamily, fontSize: typography.small, marginTop: spacing.xs }, photoError: { color: colors.error } });
