import React, { useCallback, useEffect, useMemo, useState } from 'react';
import client from '../api/client';
import ChartCard from '../components/ChartCard';
import Card from '../components/Card';
import EmptyState from '../components/EmptyState';
import { downloadCsv, printReport } from '../utils/export';
import { formatKes, formatNumber, formatTime, formatWeekday } from '../utils/formatters';

const today = new Date().toISOString().slice(0, 10);
const monthStart = `${today.slice(0, 7)}-01`;
const cash = formatKes;
function Progress({ value }) { const safe = Math.max(0, Number(value || 0)); return <div className="progress-wrap"><div className="progress-track"><span style={{ width: `${Math.min(safe, 100)}%` }} /></div><strong>{Math.round(safe)}%</strong></div>; }
function Stat({ label, value, note, accent }) { return <Card className={accent ? 'stat-accent' : ''}><span className="muted">{label}</span><div className="stat-value">{value}</div>{note && <small className="stat-note">{note}</small>}</Card>; }

export default function Dashboard() {
  const [range, setRange] = useState({ from: monthStart, to: today }); const [draft, setDraft] = useState(range);
  const [totals, setTotals] = useState(null); const [targets, setTargets] = useState([]); const [reps, setReps] = useState([]); const [products, setProducts] = useState([]); const [outlets, setOutlets] = useState([]); const [overdue, setOverdue] = useState([]);
  const [amounts, setAmounts] = useState({}); const [repSearch, setRepSearch] = useState(''); const [sortBy, setSortBy] = useState('sales'); const [error, setError] = useState(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(null); const [updatedAt, setUpdatedAt] = useState(null);
  const [focus, setFocus] = useState(() => localStorage.getItem('dashboardFocus') || 'sales'); const [autoRefresh, setAutoRefresh] = useState(() => localStorage.getItem('dashboardAutoRefresh') === 'true'); const [compact, setCompact] = useState(() => localStorage.getItem('dashboardCompact') === 'true'); const [overdueDays, setOverdueDays] = useState(7); const [goal, setGoal] = useState(() => Number(localStorage.getItem('dashboardGoal') || 0)); const [note, setNote] = useState(() => localStorage.getItem('dashboardNote') || ''); const [showDaily, setShowDaily] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(null); const params = { from: `${range.from}T00:00:00.000Z`, to: `${range.to}T23:59:59.999Z` }; try { const [a,b,c,d,e,f] = await Promise.all([client.get('/dashboard/totals',{params}),client.get('/targets',{params:{month:range.from.slice(0,7)}}),client.get('/reps'),client.get('/products'),client.get('/outlets'),client.get('/dashboard/overdue-outlets',{params:{days:overdueDays}})]); setTotals(a.data); setTargets(b.data.targets || []); setReps(c.data.reps || []); setProducts(d.data.products || []); setOutlets(e.data.outlets || []); setOverdue(f.data.overdueOutlets || []); setUpdatedAt(new Date()); } catch (err) { setError(err?.response?.data?.error?.message || 'Failed to load the dashboard.'); } finally { setLoading(false); } }, [range, overdueDays]);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { localStorage.setItem('dashboardFocus', focus); localStorage.setItem('dashboardAutoRefresh', autoRefresh); localStorage.setItem('dashboardCompact', compact); localStorage.setItem('dashboardGoal', String(goal)); localStorage.setItem('dashboardNote', note); }, [focus, autoRefresh, compact, goal, note]);
  useEffect(() => { if (!autoRefresh) return undefined; const timer = window.setInterval(load, 60000); return () => window.clearInterval(timer); }, [autoRefresh, load]);
  const targetByRep = useMemo(() => Object.fromEntries(targets.map((x) => [x.repId, Number(x.amount || 0)])), [targets]);
  const productById = useMemo(() => Object.fromEntries(products.map((x) => [x.id, x])), [products]); const outletById = useMemo(() => Object.fromEntries(outlets.map((x) => [x.id, x])), [outlets]);
  const repRows = useMemo(() => reps.filter((rep) => rep.role === 'rep').map((rep) => { const sales = Number(totals?.byRep?.[rep.id] || 0), target = targetByRep[rep.id] || 0; return { ...rep, sales, target, progress: target ? sales / target * 100 : 0, gap: Math.max(0, target-sales) }; }).filter((x) => x.name?.toLowerCase().includes(repSearch.toLowerCase())).sort((a,b) => sortBy === 'name' ? a.name.localeCompare(b.name) : sortBy === 'progress' ? b.progress-a.progress : b.sales-a.sales), [reps, totals, targetByRep, repSearch, sortBy]);
  const metrics = useMemo(() => { if (!totals) return {}; const byDay = Object.entries(totals.byDay || {}), days = Math.max(1, Math.round((new Date(`${range.to}T00:00:00Z`) - new Date(`${range.from}T00:00:00Z`))/86400000)+1), best = [...byDay].sort((a,b) => b[1]-a[1])[0], target = Object.values(targetByRep).reduce((a,b) => a+b,0), todayOfMonth = new Date().getUTCDate(), daysInMonth = new Date(new Date().getUTCFullYear(), new Date().getUTCMonth()+1, 0).getDate(); return { days, best, target, attainment: target ? totals.grandTotal/target*100 : 0, average: totals.count ? totals.grandTotal/totals.count : 0, daily: totals.grandTotal/days, forecast: totals.grandTotal/Math.max(1,todayOfMonth)*daysInMonth }; }, [totals, range, targetByRep]);
  const productsRanked = useMemo(() => Object.entries(totals?.byProduct || {}).map(([id,sales]) => ({ id, name: productById[id]?.name || 'Uncatalogued product', sales })).sort((a,b) => b.sales-a.sales).slice(0,5), [totals, productById]);
  const outletsRanked = useMemo(() => Object.entries(totals?.byOutlet || {}).map(([id,sales]) => ({ id, name: outletById[id]?.name || 'Unknown outlet', sales })).sort((a,b) => b.sales-a.sales).slice(0,5), [totals, outletById]); const atRisk = repRows.filter((x) => x.target && x.progress < 60).sort((a,b) => a.progress-b.progress);
  const dailyRows = useMemo(() => Object.entries(totals?.byDay || {}).map(([date,sales]) => ({ date, sales, weekday: formatWeekday(`${date}T00:00:00Z`) })).sort((a,b) => b.date.localeCompare(a.date)), [totals]);
  const categoryRows = useMemo(() => Object.entries(totals?.byProduct || {}).reduce((list, [id, sales]) => { const name = productById[id]?.category || 'Uncategorised'; const found = list.find((x) => x.name === name); if (found) found.sales += Number(sales); else list.push({ name, sales: Number(sales) }); return list; }, []).sort((a,b) => b.sales-a.sales), [totals, productById]);
  const leader = repRows[0]; const activeSellers = repRows.filter((x) => x.sales > 0); const goalProgress = goal ? totals?.grandTotal / goal * 100 : 0; const targetCoverage = repRows.length ? repRows.filter((x) => x.target > 0).length / repRows.length * 100 : 0;
  async function saveTarget(id) { setSaving(id); try { await client.put(`/targets/${id}`, { month: range.from.slice(0,7), amount: Number(amounts[id] ?? targetByRep[id] ?? 0) }); await load(); } catch (err) { setError(err?.response?.data?.error?.message || 'Failed to save target.'); } finally { setSaving(null); } }
  function preset(kind) { const now = new Date(); const from = kind === 'today' ? today : kind === '7d' ? new Date(now-6*86400000).toISOString().slice(0,10) : kind === '30d' ? new Date(now-29*86400000).toISOString().slice(0,10) : monthStart; const next = {from,to:today}; setDraft(next); setRange(next); }
  if (loading && !totals) return <><div className="page-heading"><span className="eyebrow">COMMAND CENTER</span><h1>Sales overview</h1></div><Card><div className="skeleton" /><div className="skeleton" /><div className="skeleton" /></Card></>;
  if (!totals) return <div className="error-banner">{error || 'No dashboard data is available.'}</div>;
  const exportRows = [['Summary','Range total',totals.grandTotal],['Summary','Transactions',totals.count],['Summary','Target attainment',`${Math.round(metrics.attainment)}%`],['Summary','Forecast',metrics.forecast],...Object.entries(totals.byDay || {}).map(([date,total]) => ['Daily sales',date,total]),...repRows.map((x) => ['Representative',x.name,x.sales])];
  return <><div className="page-heading dashboard-heading"><span className="eyebrow">COMMAND CENTER</span><h1>Sales overview</h1><p className="muted">{range.from} to {range.to} performance and daily momentum. {updatedAt && <span className="updated-time">Updated {formatTime(updatedAt)}</span>}</p><div className="quick-filters">{[['today','Today'],['7d','Last 7 days'],['30d','Last 30 days'],['month','This month']].map(([key,label]) => <button key={key} className="filter-chip" onClick={() => preset(key)}>{label}</button>)}</div><div className="filter-row"><label>From <input type="date" value={draft.from} max={draft.to} onChange={(e) => setDraft({...draft,from:e.target.value})} /></label><label>To <input type="date" value={draft.to} min={draft.from} max={today} onChange={(e) => setDraft({...draft,to:e.target.value})} /></label><button className="ui-button ui-button-primary" onClick={() => setRange(draft)}>Apply range</button><button className="ui-button ui-button-secondary" onClick={load}>Refresh</button></div><p><button className="ui-button ui-button-secondary" onClick={() => downloadCsv(`brandsphere-dashboard-${range.from}-${range.to}.csv`,['Section','Label','Value'],exportRows)}>Export CSV</button>{' '}<button className="ui-button ui-button-secondary" onClick={() => printReport('Brandsphere dashboard',['Section','Label','Value'],exportRows)}>Print report</button></p></div>{error && <div className="error-banner">{error}</div>}
  <Card title="Dashboard controls" className="dashboard-controls"><div className="control-grid"><label>View focus<select className="control" value={focus} onChange={(e) => setFocus(e.target.value)}><option value="sales">Sales momentum</option><option value="targets">Target delivery</option><option value="visits">Outlet coverage</option></select></label><label>Visit window<select className="control" value={overdueDays} onChange={(e) => setOverdueDays(Number(e.target.value))}><option value="3">3 days</option><option value="7">7 days</option><option value="14">14 days</option><option value="30">30 days</option></select></label><label>Personal range goal (KES)<input className="control" type="number" min="0" value={goal || ''} placeholder="Optional goal" onChange={(e) => setGoal(Number(e.target.value))} /></label><label>Manager note<input className="control" maxLength="120" value={note} placeholder="Add a focus note" onChange={(e) => setNote(e.target.value)} /></label></div><div className="dashboard-toggles"><button className={`toggle-button ${autoRefresh ? 'is-on' : ''}`} onClick={() => setAutoRefresh(!autoRefresh)}>{autoRefresh ? 'Auto-refresh on' : 'Auto-refresh off'}</button><button className={`toggle-button ${compact ? 'is-on' : ''}`} onClick={() => setCompact(!compact)}>{compact ? 'Comfortable view' : 'Compact view'}</button><span className="muted">Preferences are saved on this device.</span></div></Card>
  <div className={`stat-grid dashboard-stat-grid ${compact ? 'is-compact' : ''}`}><Stat accent label="Range total" value={cash(totals.grandTotal)} note={`${metrics.days} reporting days`} /><Stat label="Transactions" value={formatNumber(totals.count)} note={`${cash(metrics.average)} average sale`} /><Stat label="Active reps" value={Object.keys(totals.byRep || {}).length} note={`${activeSellers.length} with sales`} /><Stat label="Daily average" value={cash(metrics.daily)} note="Across selected range" /><Stat label="Best day" value={metrics.best ? cash(metrics.best[1]) : '—'} note={metrics.best?.[0] || 'No sales yet'} /><Stat label="Month forecast" value={cash(metrics.forecast)} note="Pace-based projection" /></div>
  <div className="grid-2"><ChartCard title="Sales by day" data={totals.byDay} /><Card title="Target health"><div className="target-health"><div><span className="health-number">{Math.round(metrics.attainment)}%</span><span className="muted">portfolio attainment</span></div><Progress value={metrics.attainment} /><p className="muted">{metrics.target ? `${cash(totals.grandTotal)} of ${cash(metrics.target)} assigned targets` : 'Set team targets below to track portfolio attainment.'}</p></div></Card></div>
  <div className="grid-3 dashboard-insights"><Card title="Personal goal"><div className="mini-metric"><strong>{goal ? `${Math.round(goalProgress)}%` : '—'}</strong><span>{goal ? `${cash(Math.max(0, goal-totals.grandTotal))} remaining` : 'Set an optional dashboard goal above.'}</span></div>{goal > 0 && <Progress value={goalProgress} />}</Card><Card title="Team coverage"><div className="mini-metric"><strong>{Math.round(targetCoverage)}%</strong><span>{repRows.filter((x) => x.target > 0).length} of {repRows.length} reps have targets.</span></div><Progress value={targetCoverage} /></Card><Card title="Team leader"><div className="mini-metric"><strong>{leader?.name || '—'}</strong><span>{leader ? `${cash(leader.sales)} · ${Math.round(leader.progress)}% to target` : 'Sales will appear after activity begins.'}</span></div></Card></div>
  <div className="grid-2 dashboard-detail-grid"><Card title="Sales pulse"><div className="pulse-list"><div><span>Leading rep</span><strong>{leader?.name || 'No sales recorded'}</strong></div><div><span>Sales per active rep</span><strong>{cash(activeSellers.length ? totals.grandTotal / activeSellers.length : 0)}</strong></div><div><span>Transactions per rep</span><strong>{activeSellers.length ? (totals.count / activeSellers.length).toFixed(1) : '0'}</strong></div><div><span>Focus</span><strong>{focus === 'sales' ? 'Daily momentum' : focus === 'targets' ? 'Target delivery' : 'Outlet coverage'}</strong></div></div>{note && <p className="manager-note">“{note}”</p>}</Card><Card title="Category mix"><ol className="rank-list">{categoryRows.length ? categoryRows.slice(0,5).map((x, i) => <li key={x.name}><span className="rank-number">{i+1}</span><strong>{x.name}</strong><span>{cash(x.sales)} · {Math.round(x.sales / Math.max(1, totals.grandTotal) * 100)}%</span></li>) : <EmptyState title="No category sales" message="Category mix appears once product sales are recorded." />}</ol></Card></div>
  <Card title="Daily sales ledger"><div className="ledger-heading"><p className="muted">Review the latest days, their weekday pattern, and share of range revenue.</p><button className="ui-button ui-button-secondary" onClick={() => setShowDaily(!showDaily)}>{showDaily ? 'Hide ledger' : 'Show ledger'}</button></div>{showDaily && <div className="table-wrap"><table><thead><tr><th>Date</th><th>Day</th><th>Sales</th><th>Range share</th></tr></thead><tbody>{dailyRows.map((x) => <tr key={x.date}><td>{x.date}</td><td>{x.weekday}</td><td>{cash(x.sales)}</td><td><Progress value={x.sales / Math.max(1, totals.grandTotal) * 100} /></td></tr>)}</tbody></table></div>}</Card>
  <div className="grid-2 dashboard-detail-grid"><Card title="Performance alerts"><div className="alert-list">{atRisk.length ? atRisk.slice(0,4).map((x) => <div className="alert-row" key={x.id}><div><strong>{x.name}</strong><span>{cash(x.gap)} remaining to target</span></div><Progress value={x.progress} /></div>) : <EmptyState title="Targets are on track" message="No representatives are below 60% of an assigned target." />}</div></Card><Card title="Visit attention"><div className="visit-summary"><span className="visit-count">{overdue.length}</span><div><strong>outlets overdue for a visit</strong><p className="muted">Not visited in the last seven days.</p></div></div>{overdue.length > 0 && <div className="overdue-names">{overdue.slice(0,5).map((x) => <span key={x.id}>{x.name}</span>)}{overdue.length > 5 && <span>+{overdue.length-5} more</span>}</div>}</Card></div>
  <div className="grid-2 dashboard-detail-grid"><Card title="Top products"><ol className="rank-list">{productsRanked.length ? productsRanked.map((x,i) => <li key={x.id}><span className="rank-number">{i+1}</span><strong>{x.name}</strong><span>{cash(x.sales)}</span></li>) : <EmptyState title="No product sales" message="Product rankings will appear after sales are recorded." />}</ol></Card><Card title="Top outlets"><ol className="rank-list">{outletsRanked.length ? outletsRanked.map((x,i) => <li key={x.id}><span className="rank-number">{i+1}</span><strong>{x.name}</strong><span>{cash(x.sales)}</span></li>) : <EmptyState title="No outlet sales" message="Outlet rankings will appear after sales are recorded." />}</ol></Card></div>
  <Card title={`Team performance · ${range.from.slice(0,7)}`}><div className="table-toolbar"><label>Find a representative <input className="control" value={repSearch} placeholder="Search name" onChange={(e) => setRepSearch(e.target.value)} /></label><label>Sort by <select className="control" value={sortBy} onChange={(e) => setSortBy(e.target.value)}><option value="sales">Sales</option><option value="progress">Target progress</option><option value="name">Name</option></select></label><span className="muted">{repRows.length} representatives</span></div><div className="table-wrap"><table><thead><tr><th>Representative</th><th>Sales</th><th>Target (KES)</th><th>Progress</th><th>Target status</th><th /></tr></thead><tbody>{repRows.map((x) => { const value = amounts[x.id] ?? (x.target || ''); const status = !x.target ? 'Not set' : x.progress >= 100 ? 'Achieved' : x.progress >= 60 ? 'In progress' : 'At risk'; return <tr key={x.id}><td><strong>{x.name}</strong><br /><small className="muted">{x.active === false ? 'Inactive' : 'Active'}</small></td><td>{cash(x.sales)}</td><td><input aria-label={`${x.name} target`} type="number" min="0" step="1" value={value} onChange={(e) => setAmounts({...amounts,[x.id]:e.target.value})} /></td><td><Progress value={x.progress} /></td><td><span className={`status-pill ${x.target ? (x.progress >= 100 ? 'status-good' : x.progress >= 60 ? 'status-watch' : 'status-risk') : ''}`}>{status}</span></td><td><button className="ui-button ui-button-secondary" type="button" disabled={saving === x.id} onClick={() => saveTarget(x.id)}>{saving === x.id ? 'Saving…' : 'Save target'}</button></td></tr>; })}</tbody></table></div></Card></>;
}
