import React, { useEffect, useMemo, useState } from 'react';
import client from '../api/client';
import ChartCard from '../components/ChartCard';
import RepTable from '../components/RepTable';
import Card from '../components/Card';
import { downloadCsv, printReport } from '../utils/export';

const today = new Date().toISOString().slice(0, 10);
const monthStart = `${today.slice(0, 7)}-01`;

export default function Dashboard() {
  const [range, setRange] = useState({ from: monthStart, to: today }); const [draft, setDraft] = useState(range); const [totals, setTotals] = useState(null); const [targets, setTargets] = useState([]); const [reps, setReps] = useState([]); const [amounts, setAmounts] = useState({}); const [error, setError] = useState(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(null);
  useEffect(() => { setLoading(true); const params = { from: `${range.from}T00:00:00.000Z`, to: `${range.to}T23:59:59.999Z` }; Promise.all([client.get('/dashboard/totals', { params }), client.get('/targets', { params: { month: range.from.slice(0, 7) } }), client.get('/reps')]).then(([totalsResponse, targetsResponse, repsResponse]) => { setTotals(totalsResponse.data); setTargets(targetsResponse.data.targets); setReps(repsResponse.data.reps); }).catch((err) => setError(err?.response?.data?.error?.message || 'Failed to load performance')).finally(() => setLoading(false)); }, [range]);
  const targetByRep = useMemo(() => Object.fromEntries(targets.map((target) => [target.repId, target.amount])), [targets]);
  async function saveTarget(repId) { setSaving(repId); try { await client.put(`/targets/${repId}`, { month: range.from.slice(0, 7), amount: Number(amounts[repId] ?? targetByRep[repId] ?? 0) }); const { data } = await client.get('/targets', { params: { month: range.from.slice(0, 7) } }); setTargets(data.targets); } catch (err) { setError(err?.response?.data?.error?.message || 'Failed to save target'); } finally { setSaving(null); } }
  if (loading) return <><div className="page-heading"><span className="eyebrow">COMMAND CENTER</span><h1>Sales overview</h1></div><Card><div className="skeleton" /><div className="skeleton" /><div className="skeleton" /></Card></>;
  if (error) return <div className="error-banner">{error}</div>; if (!totals) return null;
  const exportRows = [['Summary', 'Range total', totals.grandTotal], ['Summary', 'Transactions', totals.count], ...Object.entries(totals.byDay || {}).map(([date, total]) => ['Daily sales', date, total]), ...Object.entries(totals.byRep || {}).map(([repId, total]) => ['Representative sales', repId, total])];
  return <><div className="page-heading"><span className="eyebrow">COMMAND CENTER</span><h1>Sales overview</h1><p className="muted">{range.from} to {range.to} performance and daily momentum.</p><div className="filter-row"><label>From <input type="date" value={draft.from} max={draft.to} onChange={(event) => setDraft({ ...draft, from: event.target.value })} /></label><label>To <input type="date" value={draft.to} min={draft.from} onChange={(event) => setDraft({ ...draft, to: event.target.value })} /></label><button className="ui-button ui-button-primary" onClick={() => { setError(null); setRange(draft); }}>Apply range</button></div><p><button className="ui-button ui-button-secondary" onClick={() => downloadCsv(`brandsphere-dashboard-${range.from}-${range.to}.csv`, ['Section', 'Label', 'Value'], exportRows)}>Export CSV</button>{' '}<button className="ui-button ui-button-secondary" onClick={() => printReport('Brandsphere dashboard', ['Section', 'Label', 'Value'], exportRows)}>Export PDF</button></p></div><div className="stat-grid"><Card><span className="muted">Range total</span><div className="stat-value">KES {totals.grandTotal.toLocaleString()}</div></Card><Card><span className="muted">Transactions</span><div className="stat-value">{totals.count}</div></Card><Card><span className="muted">Active reps</span><div className="stat-value">{Object.keys(totals.byRep || {}).length}</div></Card></div><div className="grid-2"><ChartCard title="Sales by day" data={totals.byDay} /><RepTable byRep={totals.byRep} /></div><Card title={`Targets · ${range.from.slice(0, 7)}`}><div className="table-wrap"><table><thead><tr><th>Representative</th><th>Current</th><th>Target (KES)</th><th>Progress</th><th /></tr></thead><tbody>{reps.filter((rep) => rep.role === 'rep').map((rep) => { const current = Number(totals.byRep[rep.id] || 0); const target = Number(targetByRep[rep.id] || 0); const value = amounts[rep.id] ?? (target || ''); const progress = target ? Math.round((current / target) * 100) : 0; return <tr key={rep.id}><td>{rep.name}</td><td>KES {current.toLocaleString()}</td><td><input aria-label={`${rep.name} target`} type="number" min="0" step="1" value={value} onChange={(event) => setAmounts({ ...amounts, [rep.id]: event.target.value })} /></td><td>{target ? `${progress}%` : 'Not set'}</td><td><button className="ui-button ui-button-secondary" type="button" disabled={saving === rep.id} onClick={() => saveTarget(rep.id)}>{saving === rep.id ? 'Saving…' : 'Save target'}</button></td></tr>; })}</tbody></table></div></Card></>;
}
