import React, { useEffect, useState } from 'react';
import client from '../api/client';
import Card from '../components/Card';
import Button from '../components/Button';
import EmptyState from '../components/EmptyState';
const initial = { name: '', address: '', lat: '', lng: '', assignedRepId: '' };

function outletPayload(form) {
  return { name: form.name, address: form.address, location: { lat: Number(form.lat), lng: Number(form.lng) }, assignedRepId: form.assignedRepId };
}

export default function OutletsPage() {
  const [outlets, setOutlets] = useState([]); const [reps, setReps] = useState([]); const [overdue, setOverdue] = useState({ days: 7, overdueOutlets: [] }); const [days, setDays] = useState(''); const [form, setForm] = useState(initial); const [editing, setEditing] = useState(null); const [edit, setEdit] = useState(initial); const [error, setError] = useState(null);
  async function load() { const [{ data: outletData }, { data: repData }, { data: overdueData }] = await Promise.all([client.get('/outlets'), client.get('/reps'), client.get('/dashboard/overdue-outlets', { params: days ? { days: Number(days) } : {} })]); setOutlets(outletData.outlets); setReps(repData.reps); setOverdue(overdueData); }
  useEffect(() => { load().catch(() => setError('Failed to load outlets')); }, [days]);
  async function submit(event) { event.preventDefault(); setError(null); try { await client.post('/outlets', { ...outletPayload(form), active: true }); setForm(initial); await load(); } catch (err) { setError(err.response?.data?.error?.message || 'Failed to create outlet'); } }
  async function saveEdit(event) { event.preventDefault(); setError(null); try { await client.patch(`/outlets/${editing.id}`, outletPayload(edit)); setEditing(null); await load(); } catch (err) { setError(err.response?.data?.error?.message || 'Failed to update outlet'); } }
  async function toggle(outlet) { setError(null); try { await client.patch(`/outlets/${outlet.id}/status`, { active: !(outlet.active !== false) }); await load(); } catch (err) { setError(err.response?.data?.error?.message || 'Failed to update outlet status'); } }
  function beginEdit(outlet) { setEditing(outlet); setEdit({ name: outlet.name, address: outlet.address || '', lat: String(outlet.location?.lat ?? ''), lng: String(outlet.location?.lng ?? ''), assignedRepId: outlet.assignedRepId || '' }); }
  function fields(values, setValues) { return <>{[['name','Name'],['address','Address'],['lat','Latitude'],['lng','Longitude']].map(([key,label]) => <div className="field" key={key}><label>{label}</label><input required type={key === 'lat' || key === 'lng' ? 'number' : 'text'} step={key === 'lat' || key === 'lng' ? 'any' : undefined} value={values[key]} onChange={(event) => setValues({ ...values, [key]: event.target.value })} /></div>)}<div className="field"><label>Assigned rep</label><select value={values.assignedRepId} onChange={(event) => setValues({ ...values, assignedRepId: event.target.value })}><option value="">Unassigned</option>{reps.filter((rep) => rep.active !== false || rep.id === values.assignedRepId).map((rep) => <option key={rep.id} value={rep.id}>{rep.name}</option>)}</select></div></>; }
  const overdueIds = new Set(overdue.overdueOutlets.map((outlet) => outlet.id));
  return <><div className="page-heading"><span className="eyebrow">FIELD NETWORK</span><h1>Outlets</h1><p className="muted">Manage locations and assignment coverage without deleting historical sales records.</p></div>{error && <div className="error-banner">{error}</div>}<Card><div className="field"><label>Overdue after days without a geofenced visit</label><input type="number" min="1" max="365" placeholder={`Default: ${overdue.days}`} value={days} onChange={(event) => setDays(event.target.value)} /></div><p className="muted">{overdue.overdueOutlets.length} active outlet{overdue.overdueOutlets.length === 1 ? '' : 's'} have not been visited in the last {overdue.days} days.</p></Card><div className="grid-2"><Card title="Create outlet"><form className="form-grid" onSubmit={submit}>{fields(form, setForm)}<Button type="submit">Create outlet</Button></form></Card><Card title={`${outlets.length} locations`} >{outlets.length ? <div className="table-wrap"><table><thead><tr><th>Name</th><th>Address</th><th>Assigned rep</th><th>Visit alert</th><th>Status</th><th>Actions</th></tr></thead><tbody>{outlets.map((outlet) => <tr key={outlet.id}><td>{outlet.name}</td><td>{outlet.address || 'No address'}</td><td>{reps.find((rep) => rep.id === outlet.assignedRepId)?.name || 'Unassigned'}</td><td>{outlet.active === false ? '—' : overdueIds.has(outlet.id) ? `Overdue (${overdue.days}d+)` : 'Current'}</td><td>{outlet.active === false ? 'Inactive' : 'Active'}</td><td><Button variant="secondary" onClick={() => beginEdit(outlet)}>Edit</Button>{' '}<Button variant="secondary" onClick={() => toggle(outlet)}>{outlet.active === false ? 'Reactivate' : 'Deactivate'}</Button></td></tr>)}</tbody></table></div> : <EmptyState title="No outlets yet" message="Create the first location to build your field plan." />}</Card></div>{editing && <div className="ui-card" style={{ marginTop: 18 }}><h2>Edit {editing.name}</h2><form className="form-grid" onSubmit={saveEdit}>{fields(edit, setEdit)}<div><Button type="submit">Save changes</Button>{' '}<Button type="button" variant="secondary" onClick={() => setEditing(null)}>Cancel</Button></div></form></div>}</>;
}
