import React, { useEffect, useState } from 'react';
import client from '../api/client';
import Card from '../components/Card';
import EmptyState from '../components/EmptyState';
import { downloadCsv, printReport } from '../utils/export';
import { formatKes } from '../utils/formatters';

const today = new Date().toISOString().slice(0, 10);
const monthStart = `${today.slice(0, 7)}-01`;

export default function ReconciliationPage() {
  const [draft, setDraft] = useState({ from: monthStart, to: today }); const [range, setRange] = useState(draft); const [result, setResult] = useState(null); const [error, setError] = useState(null);
  useEffect(() => { setResult(null); client.get('/mpesa/reconciliation', { params: { from: `${range.from}T00:00:00.000Z`, to: `${range.to}T23:59:59.999Z` } }).then(({ data }) => setResult(data)).catch(() => setError('Failed to load reconciliation')); }, [range]);
  if (error) return <div className="error-banner">{error}</div>; if (!result) return <Card><div className="skeleton" /><div className="skeleton" /></Card>;
  const reported = result.matches.reduce((sum, item) => sum + Number(item.sale.total), 0) + result.unmatchedSales.reduce((sum, sale) => sum + Number(sale.total), 0); const collected = result.matches.reduce((sum, item) => sum + Number(item.transaction.amount), 0); const variance = collected - reported; const rows = [...result.unmatchedSales.map((sale) => ['Sale', sale.id, sale.repId, sale.total, sale.timestamp]), ...(result.unmatchedTransactions || []).map((transaction) => ['M-Pesa payment', transaction.mpesaReceiptNumber || transaction.id, transaction.repId, transaction.amount, transaction.timestamp])]; const headers = ['Type', 'ID / receipt', 'Rep ID', 'Amount (KES)', 'Timestamp'];
  return <><div className="page-heading"><span className="eyebrow">MONEY CONTROL</span><h1>M-Pesa reconciliation</h1><p className="muted">Compare reported sales against collected payments.</p><div className="filter-row"><label>From <input type="date" value={draft.from} max={draft.to} onChange={(event) => setDraft({ ...draft, from: event.target.value })} /></label><label>To <input type="date" value={draft.to} min={draft.from} onChange={(event) => setDraft({ ...draft, to: event.target.value })} /></label><button className="ui-button ui-button-primary" onClick={() => { setError(null); setRange(draft); }}>Apply range</button></div><p><button className="ui-button ui-button-secondary" onClick={() => downloadCsv(`brandsphere-unmatched-${range.from}-${range.to}.csv`, headers, rows)}>Export unmatched CSV</button>{' '}<button className="ui-button ui-button-secondary" onClick={() => printReport('Brandsphere unmatched reconciliation', headers, rows)}>Print / save PDF</button></p></div><div className="stat-grid"><Card><span className="muted">Reported</span><div className="stat-value">{formatKes(reported)}</div></Card><Card><span className="muted">Collected</span><div className="stat-value">{formatKes(collected)}</div></Card><Card className={variance === 0 ? '' : 'error-banner'}><span className="muted">Variance</span><div className="stat-value">{formatKes(variance)}</div></Card></div><div className="grid-2"><Card title={`Matched (${result.matches.length})`}>{result.matches.length ? <ul>{result.matches.map(({ sale, transaction }) => <li key={transaction.id}>Sale {sale.id}: {formatKes(sale.total)} matched to {transaction.mpesaReceiptNumber || transaction.id}</li>)}</ul> : <EmptyState title="No matched payments" />}</Card><Card title={`Unmatched sales (${result.unmatchedSales.length})`}>{result.unmatchedSales.map((sale) => <li key={sale.id}>Sale {sale.id}: {formatKes(sale.total)}</li>).length ? <ul>{result.unmatchedSales.map((sale) => <li key={sale.id}>Sale {sale.id}: {formatKes(sale.total)}</li>)}</ul> : <EmptyState title="No unmatched sales" />}</Card></div></>;
}
