import React,{useCallback,useEffect,useState} from 'react';
import client from '../api/client';
import Card from '../components/Card';
import Button from '../components/Button';

const statuses=['submitted','contacted','requirements_checked','training_scheduled','placed','rejected'];
const label=s=>String(s||'').replace(/_/g,' ');
export default function ReferralRegistrationsPage(){const [rows,setRows]=useState([]);const [summary,setSummary]=useState(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [busy,setBusy]=useState('');
const load=useCallback(async()=>{try{const [r,s]=await Promise.all([client.get('/referrals'),client.get('/referrals/summary')]);setRows(r.data.referrals||[]);setSummary(s.data.summary);setError('');}catch(e){setError(e.response?.data?.error?.message||'Could not load applicant referrals');}finally{setLoading(false);}},[]);useEffect(()=>{load()},[load]);
async function advance(row,status){const note=window.prompt('Optional review note','');if(note===null)return;setBusy(row.id);try{await client.patch(`/referrals/${row.id}/status`,{status,note});await load()}catch(e){setError(e.response?.data?.error?.message||'Status update failed')}finally{setBusy('')}}
async function pay(row){const ref=window.prompt(`Enter transfer or payment reference for KSh ${Number(row.commissionAmountKsh).toLocaleString()}`);if(!ref)return;setBusy(row.id);try{await client.post(`/referrals/${row.id}/pay`,{paymentReference:ref});await load()}catch(e){setError(e.response?.data?.error?.message||'Could not record payment')}finally{setBusy('')}}
return <><div className="page-heading"><span className="eyebrow">JOBPLUS · CANDIDATE RECRUITMENT</span><h1>Applicant referrals</h1><p className="muted">Review recruiter submissions, track progress, and record commission payments against the configured campaign rule.</p></div>{error?<div className="error-banner">{error}</div>:null}<div className="grid-4">{[['Applicants',summary?.total||0],['In progress',(summary?.counts?.submitted||0)+(summary?.counts?.contacted||0)],['Placed',summary?.counts?.placed||0],['Commission due',`KSh ${(summary?.dueKsh||0).toLocaleString()}`]].map(([k,v])=><Card key={k}><small className="muted">{k}</small><h2>{v}</h2></Card>)}</div>{summary?.commissionRuleMissing?<div className="error-banner">At least one recruitment campaign has no commission rule. Configure a rate and trigger in Campaigns before promising or paying recruiter commission.</div>:null}<Card title={`${rows.length} applicant records`}><div className="table-wrap"><table><thead><tr><th>Applicant</th><th>Phone</th><th>Email</th><th>National ID</th><th>Campaign</th><th>Recruiter</th><th>Details</th><th>Progress</th><th>Commission</th><th>Action</th></tr></thead><tbody>{rows.map(row=>{const next=statuses[statuses.indexOf(row.status)+1];return <tr key={row.id}><td><strong>{row.applicantName}</strong><br/><small>{row.county}</small></td><td>{row.phone}</td><td>{row.email||'—'}</td><td>{row.applicantIdNumber||'—'}</td><td>{row.campaignName}</td><td>{row.recruiterId}</td><td>{row.education} · {label(row.passportStatus)} · NITA {row.nitaFeeStatus==='paid'?'paid':'unpaid'}</td><td>{label(row.status)}</td><td>{row.commissionConfigured?`KSh ${Number(row.commissionAmountKsh).toLocaleString()} · ${label(row.payoutStatus)}`:'Not configured'}</td><td>{row.payoutStatus==='due'?<Button disabled={busy===row.id} onClick={()=>pay(row)}>Record payment</Button>:next&&row.status!=='rejected'?<Button variant="secondary" disabled={busy===row.id} onClick={()=>advance(row,next)}>Move to {label(next)}</Button>:row.status==='rejected'?'Closed':row.status==='placed'?'Complete':'—'}</td></tr>})}</tbody></table>{loading?<p className="muted">Loading applicants…</p>:!rows.length?<p className="muted">No registrations have been submitted yet.</p>:null}</div></Card></>}
