import React, { useState } from 'react';
import { SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { startRouteTracking, stopRouteTracking } from '../location/gpsTracker';
import Card from '../components/Card';
import PrimaryButton from '../components/PrimaryButton';
import SyncStatusBadge from '../components/SyncStatusBadge';
import { colors, spacing, typography } from '../theme/tokens';

export default function HomeScreen({ navigation }) {
  const [tracking, setTracking] = useState(false);
  async function toggleTracking() { if (tracking) await stopRouteTracking(); else await startRouteTracking(); setTracking(!tracking); }
  return <SafeAreaView style={styles.container}><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>FIELD OPERATIONS</Text><Text style={styles.title}>Good morning</Text><Text style={styles.subtitle}>Keep your route moving and your records current.</Text><Card style={styles.syncCard}><Text style={styles.cardLabel}>Sync status</Text><SyncStatusBadge status="synced" /></Card><Card><Text style={styles.sectionTitle}>Today at a glance</Text><View style={styles.stats}><View><Text style={styles.statValue}>0 / 0</Text><Text style={styles.statLabel}>Outlets visited</Text></View><View><Text style={styles.statValue}>0</Text><Text style={styles.statLabel}>Sales logged</Text></View><View><Text style={styles.statValue}>KES 0</Text><Text style={styles.statLabel}>Total today</Text></View></View></Card><Card style={styles.shiftCard}><Text style={styles.sectionTitle}>{tracking ? 'Shift in progress' : 'Ready for your shift?'}</Text><Text style={styles.status}>{tracking ? 'Route tracking is active' : 'Start tracking when you leave your base'}</Text><PrimaryButton title={tracking ? 'End shift' : 'Start shift'} onPress={toggleTracking} variant={tracking ? 'secondary' : 'primary'} /></Card><Text style={styles.sectionTitle}>Quick access</Text><View style={styles.actions}><PrimaryButton title="Assigned outlets" onPress={() => navigation.navigate('Outlets')} variant="secondary" /><PrimaryButton title="Sales history" onPress={() => navigation.navigate('History')} variant="secondary" /><PrimaryButton title="Route summary" onPress={() => navigation.navigate('RouteMap')} variant="secondary" /></View></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.lg, gap: spacing.md }, eyebrow: { color: colors.primary, fontSize: 11, fontWeight: '800', letterSpacing: 1.2 }, title: { color: colors.ink, fontSize: typography.title, fontWeight: '800' }, subtitle: { color: colors.muted, fontSize: typography.body, lineHeight: 22, marginTop: -spacing.sm }, syncCard: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, cardLabel: { color: colors.ink, fontSize: typography.h3, fontWeight: '800' }, sectionTitle: { color: colors.ink, fontSize: typography.h3, fontWeight: '800', marginBottom: spacing.md }, stats: { flexDirection: 'row', justifyContent: 'space-between' }, statValue: { color: colors.primary, fontSize: 20, fontWeight: '800' }, statLabel: { color: colors.muted, fontSize: 11, marginTop: 4 }, shiftCard: { gap: spacing.sm }, status: { color: colors.muted, fontSize: typography.small, marginTop: -spacing.sm, marginBottom: spacing.xs }, actions: { gap: spacing.sm } });
