import React from 'react';
import { Ionicons } from '@expo/vector-icons';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import Card from '../components/Card';
import { useAuth } from '../auth/AuthContext';
import { useLanguage } from '../i18n/LanguageContext';
import { useTheme } from '../theme/ThemeContext';
import { radius, spacing, typography } from '../theme/tokens';
import { isBiometricUnlockEnabled, setBiometricUnlockEnabled } from '../auth/biometric';

export default function MoreScreen({ navigation }) {
  const { signOut, user } = useAuth(); const { language, setLanguage, t } = useLanguage(); const { colors, mode, setMode } = useTheme(); const [biometricEnabled, setBiometricEnabled] = React.useState(false); const styles = createStyles(colors); const destinations = [{ title: t('performance'), icon: 'trending-up-outline', screen: 'Performance' }, { title: t('shiftHistory'), icon: 'time-outline', screen: 'ShiftHistory' }, { title: t('pendingSales'), icon: 'cloud-upload-outline', screen: 'PendingSales' }, { title: t('salesHistory'), icon: 'receipt-outline', screen: 'History' }];
  React.useEffect(() => { isBiometricUnlockEnabled().then(setBiometricEnabled); }, []);
  async function toggleBiometric(enabled) { try { await setBiometricUnlockEnabled(enabled); setBiometricEnabled(enabled); } catch (error) { alert(error.message); } }
  return <SafeAreaView style={styles.container}><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>ACCOUNT</Text><View style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>{(user?.name || user?.email || 'U').slice(0, 1).toUpperCase()}</Text></View><View><Text style={styles.name}>{user?.name || 'Field representative'}</Text><Text style={styles.email}>{user?.email || 'Account settings'}</Text></View></View><Text style={styles.section}>Workspace</Text><Card style={styles.menu}>{destinations.map((item) => <Pressable key={item.screen} style={styles.row} onPress={() => navigation.navigate(item.screen)}><Ionicons name={item.icon} color={colors.primary} size={22} /><Text style={styles.rowText}>{item.title}</Text><Ionicons name="chevron-forward" color={colors.muted} size={20} /></Pressable>)}</Card><Text style={styles.section}>Settings</Text><Card style={styles.menu}><View style={styles.row}><Ionicons name="moon-outline" color={colors.primary} size={22} /><Text style={styles.rowText}>Dark mode</Text><Switch value={mode === 'dark'} onValueChange={(enabled) => setMode(enabled ? 'dark' : 'light')} trackColor={{ false: colors.border, true: colors.primarySoft }} thumbColor={mode === 'dark' ? colors.primary : colors.surface} /></View><View style={styles.row}><Ionicons name="finger-print-outline" color={colors.primary} size={22} /><Text style={styles.rowText}>Biometric unlock</Text><Switch value={biometricEnabled} onValueChange={toggleBiometric} trackColor={{ false: colors.border, true: colors.primarySoft }} thumbColor={biometricEnabled ? colors.primary : colors.surface} /></View><Pressable style={styles.row} onPress={() => setLanguage(language === 'en' ? 'sw' : 'en')}><Ionicons name="language-outline" color={colors.primary} size={22} /><Text style={styles.rowText}>Language</Text><Text style={styles.value}>{language === 'en' ? 'English' : 'Kiswahili'}</Text><Ionicons name="chevron-forward" color={colors.muted} size={20} /></Pressable></Card><Pressable style={styles.signOut} onPress={signOut}><Ionicons name="log-out-outline" color={colors.error} size={22} /><Text style={styles.signOutText}>{t('signOut')}</Text></Pressable></ScrollView></SafeAreaView>;
}
const createStyles = (colors) => StyleSheet.create({ container: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.lg, gap: spacing.md }, eyebrow: { color: colors.primary, fontFamily: typography.fontFamilyExtraBold, fontSize: 11, fontWeight: '800', letterSpacing: 1.2 }, profile: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, marginBottom: spacing.sm }, avatar: { width: 54, height: 54, alignItems: 'center', justifyContent: 'center', borderRadius: 27, backgroundColor: colors.primary }, avatarText: { color: colors.white, fontFamily: typography.fontFamilyExtraBold, fontSize: 22, fontWeight: '800' }, name: { color: colors.ink, fontFamily: typography.fontFamilyExtraBold, fontSize: typography.h2, fontWeight: '800' }, email: { color: colors.muted, fontFamily: typography.fontFamily, fontSize: typography.small, marginTop: 3 }, section: { color: colors.ink, fontFamily: typography.fontFamilyExtraBold, fontSize: typography.h3, fontWeight: '800', marginTop: spacing.sm }, menu: { padding: 0, overflow: 'hidden' }, row: { minHeight: 56, flexDirection: 'row', alignItems: 'center', gap: spacing.sm, paddingHorizontal: spacing.md, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, rowText: { flex: 1, color: colors.ink, fontFamily: typography.fontFamilySemiBold, fontSize: typography.body, fontWeight: '600' }, value: { color: colors.muted, fontFamily: typography.fontFamily, fontSize: typography.small }, signOut: { minHeight: 54, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.sm, marginTop: spacing.sm, borderWidth: 1, borderColor: colors.errorSoft, borderRadius: radius.md, backgroundColor: colors.errorSoft }, signOutText: { color: colors.error, fontFamily: typography.fontFamilyExtraBold, fontSize: typography.button, fontWeight: '800' } });
