import React,{useCallback,useState} from 'react';
import {Alert,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {useFocusEffect} from '@react-navigation/native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {getRecruitmentCampaigns,submitReferral} from '../api/referrals';
import {useTheme} from '../theme/ThemeContext';

const options={education:[['KCPE','KCPE'],['KCSE','KCSE'],['both','Both']],passportStatus:[['has_passport','Has passport'],['will_get_self_funded','Will get one'],['not_ready','Not ready']],nitaFeeStatus:[['not_paid','Not paid'],['paid','Paid']]};
export default function NewApplicantScreen({navigation}){const {colors}=useTheme();const [campaigns,setCampaigns]=useState([]);const [form,setForm]=useState({campaignId:'',applicantName:'',phone:'',county:'',education:'KCPE',passportStatus:'has_passport',nitaFeeStatus:'not_paid'});const [consent,setConsent]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState('');
useFocusEffect(useCallback(()=>{let active=true;getRecruitmentCampaigns().then(c=>{if(active){setCampaigns(c);if(!form.campaignId&&c[0])setForm(f=>({...f,campaignId:c[0].id}));}}).catch(()=>active&&setError('Campaign list unavailable. Check your connection.'));return()=>{active=false};},[]));
const field=(key,label,keyboardType)=> <View style={s.field}><Text style={[s.label,{color:colors.ink}]}>{label}</Text><TextInput value={form[key]} onChangeText={v=>setForm({...form,[key]:v})} placeholder={label} placeholderTextColor={colors.muted} keyboardType={keyboardType||'default'} style={[s.input,{color:colors.ink,borderColor:colors.border,backgroundColor:colors.surface}]}/></View>;
const choices=(key,label)=><View style={s.field}><Text style={[s.label,{color:colors.ink}]}>{label}</Text><View style={s.choices}>{options[key].map(([value,title])=><Pressable key={value} onPress={()=>setForm({...form,[key]:value})} style={[s.choice,form[key]===value&&s.chosen]}><Text style={[s.choiceText,form[key]===value&&{color:'white'}]}>{title}</Text></Pressable>)}</View></View>;
async function save(){setError('');if(!form.campaignId||form.applicantName.trim().length<2||!form.phone||!form.county||!consent){setError('Complete all fields and confirm the applicant agreed to share these details.');return;}setSaving(true);try{await submitReferral({...form,applicantName:form.applicantName.trim(),phone:form.phone.trim(),county:form.county.trim(),eligibleForWomenOnlyIntake:true,applicantConsent:true});Alert.alert('Applicant registered','The registration is now linked to your account.');navigation.goBack();}catch(e){setError(e.response?.data?.error?.message||'Registration failed. Your entries are still on this screen; please retry.');}finally{setSaving(false)}}
return <SafeAreaView style={[s.safe,{backgroundColor:colors.background}]}><ScrollView contentContainerStyle={s.content}><Text style={[s.title,{color:colors.ink}]}>Register applicant</Text><Text style={[s.note,{color:colors.muted}]}>Collect consent before entering personal details. Phone number prevents duplicate campaign registrations.</Text>{campaigns.length>1?<View style={s.field}><Text style={[s.label,{color:colors.ink}]}>Campaign</Text><View style={s.choices}>{campaigns.map(c=><Pressable key={c.id} onPress={()=>setForm({...form,campaignId:c.id})} style={[s.choice,form.campaignId===c.id&&s.chosen]}><Text style={[s.choiceText,form.campaignId===c.id&&{color:'white'}]}>{c.name}</Text></Pressable>)}</View></View>:null}{field('applicantName','Applicant full name')}{field('phone','Kenyan mobile number','phone-pad')}{field('county','County')}{choices('education','Education')}{choices('passportStatus','Passport readiness')}{choices('nitaFeeStatus','NITA fee status')}<Pressable onPress={()=>setConsent(!consent)} style={s.consent}><View style={[s.checkbox,consent&&s.checked]}><Text style={{color:'white',fontWeight:'900'}}>{consent?'✓':''}</Text></View><Text style={[s.note,{color:colors.ink,flex:1}]}>Applicant is an adult woman who consented to share these details for this recruitment campaign.</Text></Pressable>{error?<Text style={{color:colors.error,marginBottom:12}}>{error}</Text>:null}<Pressable disabled={saving||!campaigns.length} onPress={save} style={[s.button,(saving||!campaigns.length)&&{opacity:.5}]}><Text style={s.buttonText}>{saving?'Saving…':'Submit registration'}</Text></Pressable></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1},content:{padding:20,paddingBottom:40},title:{fontSize:24,fontWeight:'900'},note:{fontSize:13,lineHeight:19,marginTop:7,marginBottom:12},field:{marginTop:13},label:{fontWeight:'800',marginBottom:7},input:{borderWidth:1,borderRadius:12,padding:13,fontSize:15},choices:{flexDirection:'row',flexWrap:'wrap',gap:7},choice:{borderColor:'#D8E0EA',borderWidth:1,borderRadius:10,paddingHorizontal:11,paddingVertical:10},chosen:{backgroundColor:'#2337FF',borderColor:'#2337FF'},choiceText:{fontSize:12,fontWeight:'700',color:'#536174'},consent:{flexDirection:'row',gap:10,alignItems:'center',marginVertical:19},checkbox:{width:23,height:23,borderWidth:1,borderColor:'#AAB2C0',borderRadius:6,alignItems:'center',justifyContent:'center'},checked:{backgroundColor:'#2337FF',borderColor:'#2337FF'},button:{backgroundColor:'#CBF532',borderRadius:14,alignItems:'center',padding:15},buttonText:{fontWeight:'900',color:'#172033'}});
