import React, { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { fetchMySales } from '../api/sales';
import { fetchOutlets } from '../api/catalog';
import Card from '../components/Card';
import EmptyState from '../components/EmptyState';
import { formatKes } from '../utils/formatters';
import { colors, spacing, typography } from '../theme/tokens';

const dayKey = (date) => new Date(date).toISOString().slice(0, 10);
export default function PerformanceScreen() {
  const [sales, setSales] = useState(null); const [outlets, setOutlets] = useState([]);
  useEffect(() => { Promise.all([fetchMySales(), fetchOutlets()]).then(([loadedSales, loadedOutlets]) => { setSales(loadedSales); setOutlets(loadedOutlets); }).catch(() => setSales([])); }, []);
  const stats = useMemo(() => { if (!sales) return null; const now = Date.now(); const recent = (days) => sales.filter((sale) => now - new Date(sale.timestamp).getTime() < days * 86400000); const totals = (items) => items.reduce((sum, sale) => sum + Number(sale.total || sale.qty * sale.unitPrice || 0), 0); const byOutlet = sales.reduce((groups, sale) => ({ ...groups, [sale.outletId]: (groups[sale.outletId] || 0) + Number(sale.total || 0) }), {}); const bestId = Object.keys(byOutlet).sort((a, b) => byOutlet[b] - byOutlet[a])[0]; const activeDays = new Set(sales.map((sale) => dayKey(sale.timestamp))); let streak = 0; for (let date = new Date(); activeDays.has(dayKey(date)); date.setDate(date.getDate() - 1)) streak += 1; return { week: totals(recent(7)), month: totals(recent(30)), best: outlets.find((outlet) => outlet.id === bestId)?.name || 'No sales yet', streak }; }, [sales, outlets]);
  if (!stats) return <View style={styles.loading}><ActivityIndicator color={colors.primary} /><Text style={styles.loadingText}>Loading performance…</Text></View>;
  if (!sales.length) return <EmptyState icon="◔" title="Your performance starts here" message="Log your first sale to see trends and your top outlet." />;
  return <SafeAreaView style={styles.container}><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>PERSONAL PERFORMANCE</Text><Text style={styles.title}>Your sales pulse</Text><Text style={styles.subtitle}>Track momentum and focus your next outlet visit.</Text><View style={styles.grid}><Card style={styles.stat}><Text style={styles.value}>{formatKes(stats.week)}</Text><Text style={styles.label}>Last 7 days</Text></Card><Card style={styles.stat}><Text style={styles.value}>{formatKes(stats.month)}</Text><Text style={styles.label}>Last 30 days</Text></Card></View><Card><Text style={styles.cardLabel}>Top outlet</Text><Text style={styles.highlight}>{stats.best}</Text><Text style={styles.help}>Your highest-value outlet across recorded sales.</Text></Card><Card><Text style={styles.cardLabel}>Sales-day streak</Text><Text style={styles.highlight}>{stats.streak} day{stats.streak === 1 ? '' : 's'}</Text><Text style={styles.help}>Consecutive days with at least one logged sale.</Text></Card></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: colors.background }, loading: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.background, gap: spacing.sm }, loadingText: { color: colors.muted }, content: { padding: spacing.lg, gap: spacing.md }, eyebrow: { color: colors.primary, fontSize: 11, fontWeight: '800', letterSpacing: 1.2 }, title: { color: colors.ink, fontSize: typography.title, fontWeight: '800' }, subtitle: { color: colors.muted, fontSize: typography.body }, grid: { flexDirection: 'row', gap: spacing.sm }, stat: { flex: 1 }, value: { color: colors.primary, fontSize: 20, fontWeight: '800' }, label: { color: colors.muted, fontSize: typography.small, marginTop: spacing.xs }, cardLabel: { color: colors.muted, fontSize: typography.small, fontWeight: '700' }, highlight: { color: colors.ink, fontSize: typography.h2, fontWeight: '800', marginTop: spacing.xs }, help: { color: colors.muted, fontSize: typography.small, marginTop: spacing.xs } });
