import React, { useCallback, useState } from 'react';
import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import { Ionicons } from '@expo/vector-icons';
import { SafeAreaView } from 'react-native-safe-area-context';
import { getRecruitmentCampaigns, getReferralSummary } from '../api/referrals';
import { useTheme } from '../theme/ThemeContext';

export default function RecruiterHomeScreen({ navigation }) {
  const { colors } = useTheme(); const [campaigns, setCampaigns] = useState([]); const [summary, setSummary] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useFocusEffect(useCallback(() => { let active = true; Promise.all([getRecruitmentCampaigns(), getReferralSummary()]).then(([c,s]) => { if (active) { setCampaigns(c); setSummary(s); setError(''); } }).catch(() => active && setError('Could not refresh campaign data. Check your connection and try again.')).finally(() => active && setLoading(false)); return () => { active = false; }; }, []));
  return <SafeAreaView style={[styles.safe,{backgroundColor:colors.background}]}><ScrollView contentContainerStyle={styles.content}>
    <View style={styles.header}><View><Text style={[styles.kicker,{color:colors.primary}]}>JOBPLUS INTERNATIONAL</Text><Text style={[styles.title,{color:colors.ink}]}>Recruiter hub</Text></View><Ionicons name="people-circle-outline" size={34} color={colors.primary}/></View>
    <View style={styles.hero}><Text style={styles.heroKicker}>SAUDI ARABIA · HOMECARE</Text><Text style={styles.heroTitle}>A clear path from referral to placement.</Text><Text style={styles.heroText}>Register interested applicants, then follow each referral through review and training.</Text><Pressable style={styles.cta} onPress={() => navigation.navigate('NewApplicant')}><Text style={styles.ctaText}>Register applicant</Text><Ionicons name="arrow-forward" size={18} color="#172033"/></Pressable></View>
    <Image source={require('../../assets/jobplus-recruitment-poster.png')} resizeMode="cover" style={styles.poster} accessibilityLabel="Jobplus International Saudi Arabia homecare recruitment poster" />
    <View style={styles.stats}>{[['Registered',summary?.total || 0,'people-outline'],['In progress',(summary?.counts?.submitted || 0)+(summary?.counts?.contacted || 0)+(summary?.counts?.requirements_checked || 0)+(summary?.counts?.training_scheduled || 0),'time-outline'],['Placed',summary?.counts?.placed || 0,'checkmark-circle-outline'],['Commission due',`KSh ${Number(summary?.dueKsh || 0).toLocaleString()}`,'wallet-outline'],['Paid',`KSh ${Number(summary?.paidKsh || 0).toLocaleString()}`,'checkmark-done-outline']].map(([label,value,icon])=><View key={label} style={[styles.stat,{backgroundColor:colors.surface,borderColor:colors.border}]}><Ionicons name={icon} size={19} color={colors.primary}/><Text style={[styles.statValue,{color:colors.ink}]}>{loading?<ActivityIndicator/>:value}</Text><Text style={[styles.statLabel,{color:colors.muted}]}>{label}</Text></View>)}</View>
    <View style={[styles.info,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.section,{color:colors.ink}]}>Campaign guide</Text><Text style={[styles.body,{color:colors.muted}]}>The poster advertises a candidate salary of 1,013.23 SAR (about KSh 35,000) after training. This is not recruiter commission. Ask your manager about the campaign’s separate referral payout terms.</Text><Text style={[styles.body,{color:colors.muted,marginTop:10}]}>Applicants should be women, have KCPE or KCSE, and either hold a passport or plan to obtain one. The poster lists a KSh 3,000 NITA fee.</Text></View>
    <View style={styles.row}><Text style={[styles.section,{color:colors.ink}]}>Active campaigns</Text><Pressable onPress={()=>navigation.navigate('Applicants')}><Text style={{color:colors.primary,fontWeight:'700'}}>My applicants</Text></Pressable></View>
    {error ? <Text style={[styles.body,{color:colors.error}]}>{error}</Text> : null}{campaigns.length===0&&!loading?<Text style={[styles.body,{color:colors.muted}]}>No active campaign is assigned to your team yet. Ask your manager to add you to the recruitment team.</Text>:campaigns.map((campaign)=><View key={campaign.id} style={[styles.campaign,{backgroundColor:colors.surface,borderColor:colors.border}]}><Ionicons name="briefcase-outline" size={20} color={colors.primary}/><View style={{flex:1}}><Text style={[styles.campaignTitle,{color:colors.ink}]}>{campaign.name}</Text><Text style={[styles.body,{color:colors.muted}]}>{campaign.clientName} · {campaign.referralCommissionKsh ? `KSh ${campaign.referralCommissionKsh.toLocaleString()} commission` : 'commission not configured'}</Text></View></View>)}
  </ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1},content:{padding:20,paddingBottom:36},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:20},kicker:{fontSize:11,fontWeight:'800',letterSpacing:1.1},title:{fontSize:26,fontWeight:'900',marginTop:4},hero:{backgroundColor:'#2337FF',borderRadius:22,padding:22,marginBottom:16},heroKicker:{color:'#D6FF72',fontSize:11,fontWeight:'800',letterSpacing:1},heroTitle:{color:'white',fontSize:24,fontWeight:'900',marginTop:12},heroText:{color:'#E4E8FF',fontSize:14,lineHeight:21,marginTop:8},cta:{marginTop:18,backgroundColor:'#CBF532',borderRadius:14,padding:14,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},ctaText:{color:'#172033',fontWeight:'900'},poster:{width:'100%',height:260,borderRadius:18,marginBottom:16},stats:{flexDirection:'row',flexWrap:'wrap',gap:9,marginBottom:14},stat:{width:'31%',flexGrow:1,borderWidth:1,borderRadius:16,padding:12},statValue:{fontSize:21,fontWeight:'900',marginTop:9},statLabel:{fontSize:11,marginTop:3},info:{borderWidth:1,borderRadius:18,padding:16,marginBottom:22},section:{fontSize:17,fontWeight:'800',marginBottom:8},body:{fontSize:13,lineHeight:19},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:10},campaign:{flexDirection:'row',gap:12,alignItems:'center',padding:14,borderWidth:1,borderRadius:15,marginBottom:9},campaignTitle:{fontWeight:'800',fontSize:15}});
