import React,{useCallback,useState} from 'react';
import {ActivityIndicator,FlatList,Pressable,RefreshControl,StyleSheet,Text,View} from 'react-native';
import {useFocusEffect} from '@react-navigation/native';
import {Ionicons} from '@expo/vector-icons';
import {SafeAreaView} from 'react-native-safe-area-context';
import {getReferrals} from '../api/referrals';
import {useTheme} from '../theme/ThemeContext';

const pretty=(s='')=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export default function RecruiterApplicantsScreen({navigation}){const {colors}=useTheme();const [items,setItems]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const load=useCallback(async()=>{try{setItems(await getReferrals());setError('');}catch{setError('Could not load applicants. Check your connection.');}finally{setLoading(false);}},[]);useFocusEffect(useCallback(()=>{load();},[load]));
return <SafeAreaView style={[s.safe,{backgroundColor:colors.background}]}><View style={s.header}><View><Text style={[s.title,{color:colors.ink}]}>My applicants</Text><Text style={{color:colors.muted}}>{items.length} registrations</Text></View><Pressable onPress={()=>navigation.navigate('NewApplicant')} style={s.add}><Ionicons name="add" size={22} color="#172033"/></Pressable></View>{error?<Text style={{color:colors.error,paddingHorizontal:18}}>{error}</Text>:null}{loading?<ActivityIndicator style={{marginTop:30}} color={colors.primary}/>:<FlatList data={items} keyExtractor={i=>i.id} contentContainerStyle={{padding:16,gap:10}} refreshControl={<RefreshControl refreshing={false} onRefresh={load}/>} ListEmptyComponent={<Text style={{color:colors.muted,textAlign:'center',marginTop:50}}>No applicants yet. Register your first applicant to start tracking progress.</Text>} renderItem={({item})=><View style={[s.card,{backgroundColor:colors.surface,borderColor:colors.border}]}><View style={{flex:1}}><Text style={[s.name,{color:colors.ink}]}>{item.applicantName||'Applicant'}</Text><Text style={{color:colors.muted,marginTop:4}}>{item.phone} · {item.county}</Text><Text style={{color:colors.muted,marginTop:7,fontSize:12}}>{item.campaignName}</Text></View><Text style={s.status}>{pretty(item.status)}</Text></View>}/>}</SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1},header:{padding:20,paddingBottom:6,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},title:{fontSize:24,fontWeight:'900'},add:{width:44,height:44,borderRadius:14,backgroundColor:'#CBF532',alignItems:'center',justifyContent:'center'},card:{borderWidth:1,borderRadius:16,padding:14,flexDirection:'row',alignItems:'center',gap:8},name:{fontWeight:'800',fontSize:16},status:{backgroundColor:'#EEF0FF',color:'#2337FF',fontSize:10,fontWeight:'800',paddingHorizontal:9,paddingVertical:6,borderRadius:99,overflow:'hidden'}});
