import React, { useEffect, useMemo, useState } from 'react';
import { Linking, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import * as Location from 'expo-location';
import MapView, { Marker, Polyline } from 'react-native-maps';
import Card from '../components/Card';
import EmptyState from '../components/EmptyState';
import { getRoute } from '../api/routes';
import { fetchOutlets } from '../api/catalog';
import { radius, spacing, typography } from '../theme/tokens';
import { useTheme } from '../theme/ThemeContext';

const point = (outlet) => { const p = outlet?.location; const latitude = Number(p?.lat ?? p?._latitude); const longitude = Number(p?.lng ?? p?._longitude); return Number.isFinite(latitude) && Number.isFinite(longitude) ? { latitude, longitude } : null; };
const distance = (a, b) => { if (!a || !b) return null; const rad = (n) => n * Math.PI / 180; const dLat = rad(b.latitude - a.latitude); const dLng = rad(b.longitude - a.longitude); const h = Math.sin(dLat / 2) ** 2 + Math.cos(rad(a.latitude)) * Math.cos(rad(b.latitude)) * Math.sin(dLng / 2) ** 2; return 6371 * 2 * Math.atan2(Math.sqrt(h), Math.sqrt(1 - h)); };

export default function RouteMapScreen() {
  const { colors } = useTheme(); const styles = createStyles(colors); const [route, setRoute] = useState(null); const [outlets, setOutlets] = useState([]); const [location, setLocation] = useState(null); const [mapOpen, setMapOpen] = useState(false); const [error, setError] = useState(null);
  useEffect(() => { let mounted = true; Promise.all([getRoute(new Date().toISOString().slice(0, 10)), fetchOutlets()]).then(async ([loaded, all]) => { if (!mounted) return; setRoute(loaded || null); const ids = loaded?.plannedOutletIds || []; setOutlets(ids.length ? all.filter((outlet) => ids.includes(outlet.id)) : []); const permission = await Location.getForegroundPermissionsAsync(); if (permission.granted) { const current = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Balanced }); if (mounted) setLocation({ latitude: current.coords.latitude, longitude: current.coords.longitude }); } }).catch(() => mounted && setError('Unable to load today’s route.')); return () => { mounted = false; }; }, []);
  const visited = route?.visitedOutletIds || []; const timeline = useMemo(() => outlets.map((outlet, index) => ({ outlet, coordinate: point(outlet), state: visited.includes(outlet.id) ? 'visited' : index === outlets.findIndex((entry) => !visited.includes(entry.id)) ? 'next' : 'pending' })), [outlets, visited]); const next = timeline.find((item) => item.state === 'next'); const km = distance(location, next?.coordinate); const pings = (route?.pings || []).map((ping) => ({ latitude: ping.lat, longitude: ping.lng })).filter((p) => Number.isFinite(p.latitude) && Number.isFinite(p.longitude));
  const navigate = () => { if (!next?.coordinate) return; const { latitude, longitude } = next.coordinate; Linking.openURL(`geo:${latitude},${longitude}?q=${latitude},${longitude}(${encodeURIComponent(next.outlet.name)})`); };
  if (error) return <EmptyState title="Route unavailable" message={error} />; if (!route) return <SafeAreaView style={styles.container}><View style={styles.header}><Text style={styles.eyebrow}>TODAY’S ROUTE</Text><Text style={styles.title}>No route planned yet</Text></View><EmptyState icon="⌖" title="No route planned" message="Start your shift or add planned outlets to see your route." /></SafeAreaView>;
  return <SafeAreaView style={styles.container}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Text style={styles.eyebrow}>TODAY’S ROUTE</Text><Text style={styles.title}>{timeline.length} outlets · {visited.length} visited</Text><Text style={styles.subtitle}>Follow your outlet sequence for today.</Text></View>{next && <Card style={styles.next}><Text style={styles.nextLabel}>NEXT OUTLET</Text><Text style={styles.nextName}>{next.outlet.name}</Text><Text style={styles.subtitle}>{km == null ? 'Distance available when location is enabled' : `${km < 1 ? `${Math.round(km * 1000)} m` : `${km.toFixed(1)} km`} away`}</Text><Pressable style={styles.navigate} onPress={navigate}><Text style={styles.navigateText}>Navigate</Text></Pressable></Card>}<View style={styles.timeline}>{timeline.map((item, index) => <View key={item.outlet.id} style={styles.step}><View style={styles.rail}><View style={[styles.node, item.state === 'visited' && styles.visited, item.state === 'next' && styles.nextNode]}><Text style={styles.nodeText}>{item.state === 'visited' ? '✓' : item.state === 'next' ? '→' : '○'}</Text></View>{index < timeline.length - 1 && <View style={styles.line} />}</View><Pressable style={[styles.outlet, item.state === 'next' && styles.nextOutlet]} onPress={() => item.state === 'next' && navigate()}><Text style={styles.outletName}>{item.outlet.name}</Text><Text style={styles.outletStatus}>{item.state === 'visited' ? 'Visited' : item.state === 'next' ? 'Next up' : 'Pending'}</Text></Pressable></View>)}</View><Pressable style={styles.mapButton} onPress={() => setMapOpen((open) => !open)}><Text style={styles.mapButtonText}>{mapOpen ? 'Hide map' : 'Open map'}</Text></Pressable>{mapOpen && <View style={styles.mapShell}><MapView style={styles.map} initialRegion={next?.coordinate ? { ...next.coordinate, latitudeDelta: .04, longitudeDelta: .04 } : { latitude: -1.286, longitude: 36.817, latitudeDelta: .08, longitudeDelta: .08 }}>{pings.length > 1 && <Polyline coordinates={pings} strokeColor={colors.primary} strokeWidth={4} />}{timeline.filter((item) => item.coordinate).map((item) => <Marker key={item.outlet.id} coordinate={item.coordinate} pinColor={item.state === 'visited' ? colors.success : item.state === 'next' ? colors.primary : colors.warning} title={item.outlet.name} />)}</MapView></View>}</ScrollView></SafeAreaView>;
}
const createStyles = (colors) => StyleSheet.create({ container: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.lg, gap: spacing.md }, header: { marginBottom: spacing.xs }, eyebrow: { color: colors.primary, fontFamily: typography.fontFamilyExtraBold, fontSize: 11, fontWeight: '800', letterSpacing: 1.1 }, title: { color: colors.ink, fontFamily: typography.fontFamilyExtraBold, fontSize: typography.h2, fontWeight: '800', marginTop: 5 }, subtitle: { color: colors.muted, fontFamily: typography.fontFamily, fontSize: typography.small, marginTop: 4 }, next: { backgroundColor: colors.primarySoft, gap: 6 }, nextLabel: { color: colors.primary, fontFamily: typography.fontFamilyExtraBold, fontSize: 11, letterSpacing: 1 }, nextName: { color: colors.ink, fontFamily: typography.fontFamilyExtraBold, fontSize: typography.h3, fontWeight: '800' }, navigate: { alignSelf: 'flex-start', marginTop: 6, paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderRadius: radius.md, backgroundColor: colors.primary }, navigateText: { color: colors.white, fontFamily: typography.fontFamilyExtraBold, fontWeight: '800' }, timeline: { gap: 0 }, step: { flexDirection: 'row', minHeight: 74 }, rail: { width: 34, alignItems: 'center' }, node: { width: 28, height: 28, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: colors.border, borderRadius: 14, backgroundColor: colors.surface }, visited: { borderColor: colors.success, backgroundColor: colors.success }, nextNode: { borderColor: colors.primary, backgroundColor: colors.primarySoft }, nodeText: { color: colors.ink, fontFamily: typography.fontFamilyExtraBold, fontWeight: '800' }, line: { width: 2, flex: 1, backgroundColor: colors.border }, outlet: { flex: 1, minHeight: 55, padding: spacing.sm, marginLeft: spacing.sm, marginBottom: spacing.sm, borderRadius: radius.md, backgroundColor: colors.surface }, nextOutlet: { borderWidth: 1, borderColor: colors.primary, backgroundColor: colors.primarySoft }, outletName: { color: colors.ink, fontFamily: typography.fontFamilySemiBold, fontSize: typography.body, fontWeight: '600' }, outletStatus: { color: colors.muted, fontFamily: typography.fontFamily, fontSize: 12, marginTop: 3 }, mapButton: { alignItems: 'center', padding: spacing.sm }, mapButtonText: { color: colors.primary, fontFamily: typography.fontFamilyExtraBold, fontWeight: '800' }, mapShell: { height: 280, overflow: 'hidden', borderRadius: radius.lg }, map: { flex: 1 } });
